### PR TITLE
Fix hyper key regex

### PR DESCRIPTION
**Pull request by jameslibscie**
Hyperdrive keys and urls only contain letters `a-f` and only lowercase

### CODE REVIEW

**Comment by juliangruber** [comment]
Good catch about `a-f`, however URLs and hex are case insensitive so I wouldn't be too strict about uppercase letters

**Comment by jameslibscie** [comment]
@juliangruber should the metadata validations then also be case insensitive?

**Comment by juliangruber** [comment]
> @juliangruber should the metadata validations then also be case insensitive?

If we decide to go case insensitive here, then yes that would make sense to me

**Comment by chartgerink** [comment]
Could you provide a bit more reasoning on the `a-f` restriction? (e.g., a reference to the hypercore protocol docs) If this is based on observation, how many observations do we have to make this judgment?

**Comment by juliangruber** [comment]
> Could you provide a bit more reasoning on the `a-f` restriction? (e.g., a reference to the hypercore protocol docs) If this is based on observation, how many observations do we have to make this judgment?

I hypercore link is hex encoded, which has characters a-f and 0-9 (if that's what you mean)

**Comment by juliangruber** [comment]
also see https://github.com/datproject/dat-encoding/blob/master/index.js#L16

**Comment by chartgerink** [comment]
Ahhh I had totally missed that. Thanks for the pointer! 



PS: I love counting things in binary and in hexadecimal.

**Comment by chartgerink** [comment]
oh 😂 i did it in the pattern match for the regex instead of the regex directly, let me fix that.

**Pull request merged**
