### PR TITLE
Text specification

### PR DESCRIPTION
**Pull request by chartgerink**
This is a work in progress for the text specification. Please feel free to discuss the contents here.

🚨**this should not be merged in any case right now**🚨

### CODE REVIEW

**Comment by chartgerink** [comment]
A +1 :+1: for the relative embeds duck up from my old docs, this one wrt videos specifically

https://twitter.com/brembs/status/938337453034917889

**Comment by chartgerink** [comment]
I am thinking about how we might be introducing issues if we make all kinds of requirements wrt HTML files now, based on our text perspective, and it'll be used for other purposes at some point (e.g., HTML pages to walk through surveys that includes JavaScript code). I'm leaving myself a note 📓 here...

All main files that are text MUST be HTML, but not all HTML files that are main are text 🦐

**Comment by juliangruber** [comment]
I've been thinking about whether we can trust JS some more, and since
- modules are specifically registered to authors whose profiles are available on the internet
- node developers install untrusted code onto their computers all the time
- the code only runs in a browser view, which protects your private data

we might not want to disallow JS at all, for all the advantages it can bring our ecosystem.

If an author puts an annoying `alert()` in their code, their module wouldn't be used anyway.

**Comment by chartgerink** [comment]
Relative JS loads might be doable, although we would quickly run into a copyright issue there given the CC0 nature of the module. So, I guess that we have to balance getting 404s with the self-contained nature of the module. However, is this still a thing for the text spec in that case and not more for the module spec?

I'm doing a bit of stream-of-consciousness as the thoughts occur, also for my own documentation..

**Pull request closed without merging**
